-- ============================================================
-- PRODUCTS SEED — 12 products
-- This seed file has been emptied to remove mock products.
-- ============================================================
